spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/routedata
  redis:
    host: localhost
    jedis.pool.max-active: 8
    port: 6379
server:
  servlet:
    context-path: /deeprouterec
logging:
  level:
   edu.dlut.software.cage.deeprouterec: DEBUG
station:
  cities: 大连,北京,济南,上海,武汉,西安,重庆,成都,昆明,贵阳,南宁,广州,长沙,厦门,三亚,杭州,南京,哈尔滨,长春,沈阳
my_properties:
  request_gap: 100